version: '3'
volumes:
  web:
    external: false
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgres/data
      - ./logs:/web/log
      - web:/app
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'message_board_development'
    depends_on:
      - web
    links:
      - web
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:setup db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/message-board
      - ./logs:/web/log
      - web:/app
    ports:
      - "3000:3000"